### ISSUE TITLE
Flickering proposal feature test

### ISSUE THREAD

**Issue by Ana06** [openSUSE/osem#1561]
This tests are sometimes failing:

```
Failures:
  1) Event as an conference organizer rejects a proposal
     Failure/Error: expect(flash).to eq('Event rejected!')
       
       expected: "Event rejected!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:35:in `block (3 levels) in <top (required)>'
```

```
Failures:
  1) Event as an conference organizer accepts a proposal
     Failure/Error: expect(flash).to eq('Event accepted!')
       
       expected: "Event accepted!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:46:in `block (3 levels) in <top (required)>'
```

```
  1) Event as an conference organizer restarts review of a proposal
     Failure/Error: expect(flash).to eq('Review started!')
       
       expected: "Review started!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:59:in `block (3 levels) in <top (required)>'
  2) Event as an conference organizer accepts a proposal
     Failure/Error: expect(flash).to eq('Event accepted!')
       
       expected: "Event accepted!"
            got: "none"
       
       (compared using ==)
     # ./spec/features/proposals_spec.rb:46:in `block (3 levels) in <top (required)>'
```
