### ISSUE TITLE
Multiline code blocks are broken in event abstracts

### ISSUE THREAD

**Issue by dcermak** [openSUSE/osem#2764]
**I'm submitting a ..**
- [x] Bug Report
- [ ] Feature Request

**Current behavior:**

When creating an event, one can format the abstract using markdown and include code blocks using triple-backticks. Unfortunately, the renderer appears to concatenate all lines together into a single line and breaks more or less completely if blank lines are present.

**Expected correct behavior:**

Multiline code blocks should work like everywhere else when using markdown.

**Steps to reproduce:**

- create an event and enter a multiline code block, e.g. some yaml
- click preview and you end up with something looking like this:
![image](https://user-images.githubusercontent.com/45594031/117011646-51d46500-acee-11eb-9b62-5da8fd595083.png)
or this: 
![image](https://user-images.githubusercontent.com/45594031/117011742-6dd80680-acee-11eb-9836-3ced3b5606e0.png)
if a blank line is present in the code block.

Instead I would expect it to look like this:
```yaml
mysql:
  pkg.installed:
    - name: mysql
  service.running:
    - name: mysql

web_server:
  pkg.installed:
{% if grains['os_family'] == 'RedHat' %}
    - name: httpd
{% elif grains['os_family'] == 'Debian' %}
    - name: apache2
{% endif %}
```

**Other information:**

Visible in my proposal: https://events.opensuse.org/conferences/oSVC21/program/proposals/3562 (might not be public).
