### ISSUE TITLE
using ichain enabled = true in development

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/osem#943]
I am not able to login when I have:
```YML
# config.yml
authentication:
    ichain:
      enabled: true

# devise.rb
config.ichain_base_url = "http://localhost:3000/"
config.ichain_login_path = "/conference"
```

It ends up making `POST` request after login and hence I get:
> No route matches [POST] "/conference"
